# Generated by Django 6.0.1 on 2026-03-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('en', 'English')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('orig_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.category')),
            ],
            options={
                'unique_together': {('orig_category', 'language')},
            },
        ),
    ]
