# Generated by Django 6.0.1 on 2026-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('KAZAKH', 'Kazakh'), ('RUSSIAN', 'Russian'), ('ENGLISH', 'English')], default='English'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
