# Generated by Django 6.0.1 on 2026-04-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('en', 'English')], default='en'),
        ),
    ]
